Prepare code release
GooglingTheCancerGenome/sv-gen pull request #31
Opened 2020-03-19 23:08 UTC by arnikz

2020-03-20 14:23 UTC, lsantuari requested changes
Please address [iss33](https://github.com/GooglingTheCancerGenome/sv-gen/issues/33).

2020-03-21 14:51 UTC, arnikz commented
> Please address [iss33](https://github.com/GooglingTheCancerGenome/sv-gen/issues/33).

Done.

2020-03-23 09:43 UTC, lsantuari approved these changes

2020-03-23 09:53 UTC, lsantuari commented
We can proceed with the merge.

2020-03-23 13:17 UTC, merged